"""Pydantic models for Gemini structured output (Tool Calling)."""

from typing import List, Literal

from pydantic import BaseModel, Field


class PolygonGeometry(BaseModel):
    type: Literal["Polygon"]
    coordinates: List[List[List[float]]]


class PolygonFeature(BaseModel):
    type: Literal["Feature"]
    geometry: PolygonGeometry


class Section(BaseModel):
    """A geometric section of the quilt."""
    id: str = Field(description="Unique UUID for this section")
    type: str = Field(description="rectangle, triangle, diamond, hexagon, or polygon")
    polygon: PolygonFeature = Field(description="The GeoJSON polygon defining the shape boundaries.")
    swatchId: str = Field(description="References a valid Swatch ID from the swatches list.")


class Swatch(BaseModel):
    """A fabric material definition."""
    id: str = Field(description="Unique UUID for this swatch")
    materialType: Literal["color"]
    materialColor: str = Field(description="Hex color code (e.g. #FF5733)")


class QuiltSize(BaseModel):
    width: int
    height: int


class QuiltLayout(BaseModel):
    """The complete quilt layout and design instructions generated by the AI."""
    id: str = Field(description="Unique UUID for the entire quilt")
    name: str = Field(description="A creative, evocative name for the design (e.g., 'Autumn Ember Star')")
    size: QuiltSize
    sections: List[Section] = Field(description="List of all geometric sections in the quilt.")
    swatches: List[Swatch] = Field(description="List of all fabric colors used.")


# ---------------------------------------------------------------
# Schema utilities — single source of truth
# ---------------------------------------------------------------
def generate_json_schema() -> dict:
    """Generate JSON Schema from the authoritative Pydantic model."""
    return QuiltLayout.model_json_schema()


def generate_schema_summary() -> str:
    """Auto-generate key constraint summary from the Pydantic model.

    Since structured output (Tool Calling) already sends the full schema
    to the LLM, this focuses on enum/range constraints the model might
    violate — keeping the prompt "contract" in sync automatically.
    """
    schema = QuiltLayout.model_json_schema()
    defs = schema.get("$defs", {})

    lines = ["── KEY SCHEMA CONSTRAINTS (auto-derived from Pydantic model) ──"]

    for model_name, model_schema in sorted(defs.items()):
        props = model_schema.get("properties", {})
        for field_name, field_info in props.items():
            constraints = []
            if "enum" in field_info:
                constraints.append(
                    "one of: " + ", ".join(str(v) for v in field_info["enum"])
                )
            if "const" in field_info:
                constraints.append(f"must be: {field_info['const']}")
            if "minimum" in field_info:
                constraints.append(f"min: {field_info['minimum']}")
            if "maximum" in field_info:
                constraints.append(f"max: {field_info['maximum']}")
            if constraints:
                lines.append(
                    f"• {model_name}.{field_name}: {'; '.join(constraints)}"
                )

    lines.append(
        "• All polygon coordinate rings MUST be closed (first point == last point)"
    )

    return "\n".join(lines)
